version: '2'
services:
  config-server:
    image: adenmin/spring-petclinic-config-server:0.1.0
    container_name: config-server
    mem_limit: 512M
    ports:
      - 8888:8888

  discovery-server:
    image: adenmin/spring-petclinic-discovery-server:0.1.0
    container_name: discovery-server
    mem_limit: 512M
    depends_on:
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
      - 8761:8761

  customers-service:
    image: adenmin/spring-petclinic-customers-service:${PET_MCR_BUILD}
    container_name: customers-service
    mem_limit: 512M
    volumes:
      - ./${DISTR}:/data
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-agentpath:/data/libdrill_agent.so=drillInstallationDir=/data,adminAddress=${adminAddress}:8090,agentId=customers-service,groupId=${serviceGroupId},buildVersion=${PET_MCR_BUILD},logLevel=TRACE", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
      - 8081:8081

  visits-service:
    image: adenmin/spring-petclinic-visits-service:${PET_MCR_BUILD}
    container_name: visits-service
    mem_limit: 512M
    volumes:
      - ./${DISTR}:/data
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5009", "-agentpath:/data/libdrill_agent.so=drillInstallationDir=/data,adminAddress=${adminAddress}:8090,agentId=visits-service,groupId=${serviceGroupId},buildVersion=${PET_MCR_BUILD},logLevel=TRACE", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
      - 8082:8082
      - 5009:5009

  vets-service:
    image: adenmin/spring-petclinic-vets-service:${PET_MCR_BUILD}
    container_name: vets-service
    mem_limit: 512M
    volumes:
      - ./${DISTR}:/data
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-agentpath:/data/libdrill_agent.so=drillInstallationDir=/data,adminAddress=${adminAddress}:8090,agentId=vets-service,groupId=${serviceGroupId},buildVersion=${PET_MCR_BUILD},logLevel=TRACE", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
      - 8083:8083

  api-gateway:
    image: adenmin/spring-petclinic-api-gateway:0.1.0
    container_name: api-gateway
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
      - 8080:8080

  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    mem_limit: 512M
    environment:
      - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    ports:
      - 9411:9411

  admin-server:
    image: adenmin/spring-petclinic-admin-server:0.1.0
    container_name: admin-server
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
      - 9090:9090

  hystrix-dashboard:
    image: adenmin/spring-petclinic-hystrix-dashboard:0.1.0
    container_name: hystrix-dashboard
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
      - 7979:7979

